### ISSUE TITLE
Plugin link does not work

### ISSUE THREAD

**Issue by Apep-the-snek** [nathanfranke/discord-youtube-embed-fix#4]
https://raw.githubusercontent.com/nathanfranke/discordytproxy/main/YouTubeProxy.plugin.js gives 404 error

**Comment by nathanfranke** [comment]
Thanks for the report. Fixed in ab9368570a534824ec54f1f79776582e46a73305: https://github.com/nathanfranke/discord-youtube-embed-fix#installation
